### ISSUE TITLE
resol-vbus installations probleme

### ISSUE THREAD

**Issue by waengr** [danielwippermann/resol-vbus#14]
Hallo Daniel

Ich habe versucht dein RESOL-VBUS auf meinem Raspberry Pi 2 zu installieren.
Leider habe ich dabei einige Fehlermeldungen erhalten.
Könntest Du mir dabei vielleicht weiter helfen?

Schlussendlich versuche ich Daten aus einem Resol VBus/USB Interface Adapter zu lesen.
http://www.resol.de/index/produktdetail/kategorie/2/id/13/sprache/en

Folgendes habe ich (auf einer nackten Rasbian Installation) ausgeführt:
1. ```sudo apt-get install nodejs npm node-semver```
2. ```sudo npm -g install npm```
3. ```sudo npm install --save resol-vbus```

Beim 3. Befehl ist folgendes rausgekommen:

```
npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4

> serialport@2.1.2 install /home/pi/mystuff/resol-vbus/node_modules/serialport
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/mystuff/resol-vbus/dules/serialport/.node-gyp"
make: Entering directory '/home/pi/mystuff/resol-vbus/node_modules/serialport/build'
make: *** No rule to make target '../.node-gyp/0.10.29/common.gypi', needed by 'Makefile'.  S
make: Leaving directory '/home/pi/mystuff/resol-vbus/node_modules/serialport/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.4.13-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.jld" "--fallback-to-build" "--module=/home/pi/mystuff/resol-vbus/node_modules/serialport/builde/serialport.node" "--module_name=serialport" "--module_path=/home/pi/mystuff/resol-vbus/nodes/serialport/build/Release"
gyp ERR! cwd /home/pi/mystuff/resol-vbus/node_modules/serialport
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --modulepi/mystuff/resol-vbus/node_modules/serialport/build/Release/serialport.node --module_name=ser --module_path=/home/pi/mystuff/resol-vbus/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/mystuff/resol-vbus/node_modrialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:755:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:822:5)
node-pre-gyp ERR! System Linux 4.4.13-v7+
node-pre-gyp ERR! command "node" "/home/pi/mystuff/resol-vbus/node_modules/serialport/node_mobin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/mystuff/resol-vbus/node_modules/serialport
node-pre-gyp ERR! node -v v0.10.29
node-pre-gyp ERR! node-pre-gyp -v v0.6.26
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp build --fallback-to-build --module=/home/pi/mystuff/resol-vbus/noles/serialport/build/Release/serialport.node --module_name=serialport --module_path=/home/pi//resol-vbus/node_modules/serialport/build/Release' (1)
npm WARN install:serialport@2.1.2 serialport@2.1.2 install: `node-pre-gyp install --fallback-d`
npm WARN install:serialport@2.1.2 Exit status 1
npm WARN saveError ENOENT, open '/home/pi/mystuff/resol-vbus/package.json'
ansi-regex@2.0.0 node_modules/resol-vbus/node_modules/request/node_modules/har-validator/nodes/chalk/node_modules/has-ansi/node_modules/ansi-regex -> node_modules/ansi-regex
ansi-styles@2.2.1 node_modules/resol-vbus/node_modules/request/node_modules/har-validator/nodes/chalk/node_modules/ansi-styles -> node_modules/ansi-styles
asn1@0.2.3 node_modules/resol-vbus/node_modules/request/node_modules/http-signature/node_modupk/node_modules/asn1 -> node_modules/asn1
assert-plus@0.2.0 node_modules/resol-vbus/node_modules/request/node_modules/http-signature/noles/assert-plus -> node_modules/assert-plus
async@1.5.2 node_modules/resol-vbus/node_modules/request/node_modules/form-data/node_modules/> node_modules/async
aws-sign2@0.6.0 node_modules/resol-vbus/node_modules/request/node_modules/aws-sign2 -> node_maws-sign2
aws4@1.4.1 node_modules/resol-vbus/node_modules/request/node_modules/aws4 -> node_modules/aws
buffer-more-ints@0.0.2 node_modules/resol-vbus/node_modules/buffer-more-ints -> node_modules/more-ints
caseless@0.11.0 node_modules/resol-vbus/node_modules/request/node_modules/caseless -> node_moaseless
core-util-is@1.0.2 node_modules/resol-vbus/node_modules/request/node_modules/bl/node_modules/e-stream/node_modules/core-util-is -> node_modules/core-util-is
dashdash@1.14.0 node_modules/resol-vbus/node_modules/request/node_modules/http-signature/nodes/sshpk/node_modules/dashdash -> node_modules/dashdash
delayed-stream@1.0.0 node_modules/resol-vbus/node_modules/request/node_modules/combined-streamodules/delayed-stream -> node_modules/delayed-stream
combined-stream@1.0.5 node_modules/resol-vbus/node_modules/request/node_modules/combined-streode_modules/combined-stream
escape-string-regexp@1.0.5 node_modules/resol-vbus/node_modules/request/node_modules/har-valiode_modules/chalk/node_modules/escape-string-regexp -> node_modules/escape-string-regexp
extend@3.0.0 node_modules/resol-vbus/node_modules/request/node_modules/extend -> node_modules
extsprintf@1.0.2 node_modules/resol-vbus/node_modules/request/node_modules/http-signature/nodes/jsprim/node_modules/extsprintf -> node_modules/extsprintf
forever-agent@0.6.1 node_modules/resol-vbus/node_modules/request/node_modules/forever-agent -modules/forever-agent
generate-function@2.0.0 node_modules/resol-vbus/node_modules/request/node_modules/har-validat_modules/is-my-json-valid/node_modules/generate-function -> node_modules/generate-function
getpass@0.1.6 node_modules/resol-vbus/node_modules/request/node_modules/http-signature/node_msshpk/node_modules/getpass -> node_modules/getpass
graceful-readlink@1.0.1 node_modules/resol-vbus/node_modules/request/node_modules/har-validat_modules/commander/node_modules/graceful-readlink -> node_modules/graceful-readlink
commander@2.9.0 node_modules/resol-vbus/node_modules/request/node_modules/har-validator/node_/commander -> node_modules/commander
has-ansi@2.0.0 node_modules/resol-vbus/node_modules/request/node_modules/har-validator/node_mchalk/node_modules/has-ansi -> node_modules/has-ansi
hoek@2.16.3 node_modules/resol-vbus/node_modules/request/node_modules/hawk/node_modules/hoek _modules/hoek
boom@2.10.1 node_modules/resol-vbus/node_modules/request/node_modules/hawk/node_modules/boom _modules/boom
cryptiles@2.0.5 node_modules/resol-vbus/node_modules/request/node_modules/hawk/node_modules/cs -> node_modules/cryptiles
inherits@2.0.1 node_modules/resol-vbus/node_modules/request/node_modules/bl/node_modules/readream/node_modules/inherits -> node_modules/inherits
is-property@1.0.2 node_modules/resol-vbus/node_modules/request/node_modules/har-validator/nodes/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property -> node_mos-property
generate-object-property@1.2.0 node_modules/resol-vbus/node_modules/request/node_modules/har-or/node_modules/is-my-json-valid/node_modules/generate-object-property -> node_modules/generact-property
is-typedarray@1.0.0 node_modules/resol-vbus/node_modules/request/node_modules/is-typedarray -modules/is-typedarray
isarray@1.0.0 node_modules/resol-vbus/node_modules/request/node_modules/bl/node_modules/readaeam/node_modules/isarray -> node_modules/isarray
isstream@0.1.2 node_modules/resol-vbus/node_modules/request/node_modules/isstream -> node_modstream
jsbn@0.1.0 node_modules/resol-vbus/node_modules/request/node_modules/http-signature/node_modupk/node_modules/jsbn -> node_modules/jsbn
jodid25519@1.0.2 node_modules/resol-vbus/node_modules/request/node_modules/http-signature/nodes/sshpk/node_modules/jodid25519 -> node_modules/jodid25519
ecc-jsbn@0.1.1 node_modules/resol-vbus/node_modules/request/node_modules/http-signature/node_/sshpk/node_modules/ecc-jsbn -> node_modules/ecc-jsbn
json-schema@0.2.2 node_modules/resol-vbus/node_modules/request/node_modules/http-signature/noles/jsprim/node_modules/json-schema -> node_modules/json-schema
json-stringify-safe@5.0.1 node_modules/resol-vbus/node_modules/request/node_modules/json-striafe -> node_modules/json-stringify-safe
jsonpointer@2.0.0 node_modules/resol-vbus/node_modules/request/node_modules/har-validator/nodes/is-my-json-valid/node_modules/jsonpointer -> node_modules/jsonpointer
lodash@2.4.1 node_modules/resol-vbus/node_modules/lodash -> node_modules/lodash
mime-db@1.23.0 node_modules/resol-vbus/node_modules/request/node_modules/mime-types/node_modue-db -> node_modules/mime-db
mime-types@2.1.11 node_modules/resol-vbus/node_modules/request/node_modules/mime-types -> nodes/mime-types
form-data@1.0.0-rc4 node_modules/resol-vbus/node_modules/request/node_modules/form-data -> noles/form-data
moment@2.13.0 node_modules/resol-vbus/node_modules/moment -> node_modules/moment
moment-timezone@0.5.4 node_modules/resol-vbus/node_modules/moment-timezone -> node_modules/momezone
node-uuid@1.4.7 node_modules/resol-vbus/node_modules/request/node_modules/node-uuid -> node_mnode-uuid
numeral@1.5.3 node_modules/resol-vbus/node_modules/numeral -> node_modules/numeral
oauth-sign@0.8.2 node_modules/resol-vbus/node_modules/request/node_modules/oauth-sign -> nodes/oauth-sign
pinkie@2.0.4 node_modules/resol-vbus/node_modules/request/node_modules/har-validator/node_modnkie-promise/node_modules/pinkie -> node_modules/pinkie
pinkie-promise@2.0.1 node_modules/resol-vbus/node_modules/request/node_modules/har-validator/dules/pinkie-promise -> node_modules/pinkie-promise
process-nextick-args@1.0.7 node_modules/resol-vbus/node_modules/request/node_modules/bl/node_/readable-stream/node_modules/process-nextick-args -> node_modules/process-nextick-args
q@1.4.1 node_modules/resol-vbus/node_modules/q -> node_modules/q
qs@6.1.0 node_modules/resol-vbus/node_modules/request/node_modules/qs -> node_modules/qs
- ansi-regex@2.0.0 node_modules/resol-vbus/node_modules/request/node_modules/har-validator/noles/chalk/node_modules/strip-ansi/node_modules/ansi-regex
sntp@1.0.9 node_modules/resol-vbus/node_modules/request/node_modules/hawk/node_modules/sntp -modules/sntp
hawk@3.1.3 node_modules/resol-vbus/node_modules/request/node_modules/hawk -> node_modules/haw
sprintf@0.1.5 node_modules/resol-vbus/node_modules/sprintf -> node_modules/sprintf
assert-plus@1.0.0 node_modules/resol-vbus/node_modules/request/node_modules/http-signature/noles/sshpk/node_modules/assert-plus -> node_modules/sshpk/node_modules/assert-plus
string_decoder@0.10.31 node_modules/resol-vbus/node_modules/request/node_modules/bl/node_modudable-stream/node_modules/string_decoder -> node_modules/string_decoder
stringstream@0.0.5 node_modules/resol-vbus/node_modules/request/node_modules/stringstream -> dules/stringstream
strip-ansi@3.0.1 node_modules/resol-vbus/node_modules/request/node_modules/har-validator/nodes/chalk/node_modules/strip-ansi -> node_modules/strip-ansi
supports-color@2.0.0 node_modules/resol-vbus/node_modules/request/node_modules/har-validator/dules/chalk/node_modules/supports-color -> node_modules/supports-color
chalk@1.1.3 node_modules/resol-vbus/node_modules/request/node_modules/har-validator/node_modulk -> node_modules/chalk
tough-cookie@2.2.2 node_modules/resol-vbus/node_modules/request/node_modules/tough-cookie -> dules/tough-cookie
tunnel-agent@0.4.3 node_modules/resol-vbus/node_modules/request/node_modules/tunnel-agent -> dules/tunnel-agent
tweetnacl@0.13.3 node_modules/resol-vbus/node_modules/request/node_modules/http-signature/nodes/sshpk/node_modules/tweetnacl -> node_modules/tweetnacl
sshpk@1.8.3 node_modules/resol-vbus/node_modules/request/node_modules/http-signature/node_modhpk -> node_modules/sshpk
util-deprecate@1.0.2 node_modules/resol-vbus/node_modules/request/node_modules/bl/node_moduleble-stream/node_modules/util-deprecate -> node_modules/util-deprecate
readable-stream@2.0.6 node_modules/resol-vbus/node_modules/request/node_modules/bl/node_modulable-stream -> node_modules/readable-stream
bl@1.1.2 node_modules/resol-vbus/node_modules/request/node_modules/bl -> node_modules/bl
verror@1.3.6 node_modules/resol-vbus/node_modules/request/node_modules/http-signature/node_mosprim/node_modules/verror -> node_modules/verror
jsprim@1.2.2 node_modules/resol-vbus/node_modules/request/node_modules/http-signature/node_mosprim -> node_modules/jsprim
http-signature@1.1.1 node_modules/resol-vbus/node_modules/request/node_modules/http-signaturee_modules/http-signature
xtend@4.0.1 node_modules/resol-vbus/node_modules/request/node_modules/har-validator/node_modumy-json-valid/node_modules/xtend -> node_modules/xtend
is-my-json-valid@2.13.1 node_modules/resol-vbus/node_modules/request/node_modules/har-validat_modules/is-my-json-valid -> node_modules/is-my-json-valid
har-validator@2.0.6 node_modules/resol-vbus/node_modules/request/node_modules/har-validator -modules/har-validator
request@2.72.0 node_modules/resol-vbus/node_modules/request -> node_modules/request
/home/pi/mystuff/resol-vbus
└─┬ resol-vbus@0.15.0
  └─┬ request@2.72.0
    └─┬ http-signature@1.1.1
      └─┬ sshpk@1.8.3
        ├─┬ dashdash@1.14.0
        │ └── assert-plus@1.0.0
        └─┬ getpass@0.1.6
          └── assert-plus@1.0.0

npm WARN enoent ENOENT, open '/home/pi/mystuff/resol-vbus/package.json'
npm WARN resol-vbus No description
npm WARN resol-vbus No repository field.
npm WARN resol-vbus No README data
npm WARN resol-vbus No license field.
```

Vielen Dank und lieber Gruss
Daniel

**Comment by danielwippermann** [comment]
Hallo Daniel,

ich kann das Problem auf meinem Pi leider nicht nachvollziehen, mag aber auch daran liegen, dass ich nicht die Raspbian-eigene nodejs-Version 0.10.29 benutze, sondern ein Tool namens "nvm" (Node Version Manager) verwende, um mir zeitgemäßere Node.js-Versionen zu installieren (Version 0.10 sollte nicht mehr für Neuentwicklungen verwendet werden).

Und mit der aktuellen LTS-Version 4.4.5 funktioniert Dein Code-Schnippsel ohne Probleme:

```shell
node -v  # v4.4.5
npm -v # 2.15.5

mkdir testproject
cd testproject
npm init -y
npm install --save resol-vbus
```

Um "nvm" und ein aktuelles Node.js auf dem Pi zu installieren, kannst Du folgende Schritte ausführen:

```shell
# curl | bash - Beispiel von https://github.com/creationix/nvm
# es gibt dort aber auch eine sicherere, manuelle Installation
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash

# einmal aus- und wieder einloggen, damit nvm problemlos läuft

nvm --version # sollte die installierte Version von nvm ausgeben, aktuell 0.31.1

nvm ls-remote # für eine Liste von installierbaren Node.js-Versionen
nvm install v4.4.5 # zum Installieren des aktuellen LTS-Version
```

Ich hoffe, das hilft Dir weiter...

Ansonsten einfach noch einmal melden!

Bis dann,
Daniel

**Comment by waengr** [comment]
Hallo Daniel

Hab's geschafft die neue NVM Version zu installieren. Vielen Dank.
Danach hatte ich aber noch andere Probleme. Irgendwas von "Can't install dependency of resol-vbus on itself". Habe mich darum für ein anderes ähnliches Projekt entschieden: https://github.com/tripplet/vbus-collector
Jetzt funktioniert's.

Sorry, ich bin ein Linux Neuling. Das ganze dann noch mit NodeJS, NPM und NVM überscheitet mein gegenwärtiges Wissen :-).

Trotzdem vielen Dank für Deine Hilfe und lieber Gruss
Daniel
