### ISSUE TITLE
TypeError: No path specified

### ISSUE THREAD

**Issue by waengr** [danielwippermann/resol-vbus#16]
Hi Daniel,

I am trying to get resol-vbus running on a RaspberryPi connected via USB to the Resol USB device http://www.resol.de/index/produktdetail/kategorie/2/id/74/sprache/en-us/.
Albeit some warnings npm seemed to have installed resol-vbus and the json-live-data-server example successfully.
When running `node index.js` I get this error:

```
/home/pi/resol-vbus/examples/json-live-data-server/node_modules/q/q.js:155
                throw e;
                ^

TypeError: No path specified
    at new SerialPort (/home/pi/resol-vbus/node_modules/serialport/lib/serialport.js:92:11)
    at Connection.extend._createSerialPort (/home/pi/resol-vbus/src/serial-connection.js:208:16)
    at Connection.extend._connect (/home/pi/resol-vbus/src/serial-connection.js:192:27)
    at Connection.extend.connect (/home/pi/resol-vbus/src/serial-connection.js:78:21)
    at /home/pi/resol-vbus/examples/json-live-data-server/index.js:121:25
    at _fulfilled (/home/pi/resol-vbus/examples/json-live-data-server/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/pi/resol-vbus/examples/json-live-data-server/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/pi/resol-vbus/examples/json-live-data-server/node_modules/q/q.js:816:13)
    at /home/pi/resol-vbus/examples/json-live-data-server/node_modules/q/q.js:624:44
    at runSingle (/home/pi/resol-vbus/examples/json-live-data-server/node_modules/q/q.js:137:13)

```

Is there something missing in the `config.js` file? Is `SerialConnection` correct?

Here is mine:
```
/*! resol-vbus | Copyright (c) 2013-2017, Daniel Wippermann | MIT license */
'use strict';



var path = require('path');



var config = {

        /**
         * The port number for the HTTP server to listen to.
         * @type {Number}
         */
        httpPort: 3333,

        /**
         * The inteval in milliseconds between two writes of the logging file.
         * @type {Number}
         */
        loggingInterval: 10000,

        /**
         * The filename of the logging file.
         * @type {String}
         */
        loggingFilename: path.resolve(__dirname, 'live-data.json'),

        /**
         * The name of the `Connection` subclass to use for connecting to the VBus.
         * @type {String}
         */
        connectionClassName: 'SerialConnection',

        connectionOptions: {
                /**
                 * The host name / IP address of the VBus/LAN or Datalogger device.
                 * @type {String}
                 */
                host: '192.168.13.21',

                /**
                 * The password for the VBus/LAN or Datalogger device.
                 * @type {String}
                 */
                password: 'vbus',
        },

};



module.exports = config;
```

Many thanks in advance,
Daniel

**Comment by danielwippermann** [comment]
Hi Daniel,

yes, the `SerialConnection` for the `connectionClassName` is correct. But in addition to that the path to the TTY of the RESOL VBus/USB adapter must be specified as a `path` property in the `connectionOptions` object. Something like this should do:

```javascript
        // ... snip ...
        connectionClassName: 'SerialConnection',

        connectionOptions: {
                /**
                 * The path to the serial port.
                 * @type {String}
                 */
                path: '/dev/tty.usbserial',
        },
        // ... snip ...
```

I'm not sure what the TTY is actually called on the RPi, sorry. Just replace the `tty.usbserial` with whatever it is called in your case.

I hope that helps!

Best regards,
   Daniel

**Comment by waengr** [comment]
Hi Daniel,

Great it works now!

Many thanks for your help. I will close this issue.

Best,
Dan
