### ISSUE TITLE
not able to build/install

### ISSUE THREAD

**Issue by ArthurCoolen** [danielwippermann/resol-vbus#44]
Hi Daniel,  

I'm trying to install  your work on a raspberry to be able to read my vbus-lan however i have no experience with node.js.  So I try to just simply follow the instructions:  (i use node v8.11.1 and npm 1.4.21 and i also tried it with sudo, same error)

**git clone https://github.com/danielwippermann/resol-vbus.git**
**cd resol-vbus**
**npm install**

But this gives errors:

(node:7495) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.19.66+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/projects/resol-vbus
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/projects/resol-vbus/npm-debug.log
npm ERR! not ok code 0

pi@raspberrypi:~/projects/resol-vbus $ sudo npm install
(node:7555) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.19.66+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/projects/resol-vbus
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/projects/resol-vbus/npm-debug.log
npm ERR! not ok code 0

any clues?

Thanks in advance,  Arthur

**Comment by ArthurCoolen** [comment]
never mind, turned out to be an old nodejs install on raspberry.  My mistake :-(
