### ISSUE TITLE
Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by dm82m** [danielwippermann/resol-vbus#85]
I created an Add-on for Home Assistant but getting this error:

```
internal/modules/cjs/loader.js:818
  throw err;
  ^
Error: Cannot find module 'fs/promises'
Require stack:
- /bin/resol-vbus/src/file-list-reader.js
- /bin/resol-vbus/src/index.js
- /bin/resol-vbus/examples/resol-vbus.js
- /bin/resol-vbus/examples/json-live-data-server/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bin/resol-vbus/src/file-list-reader.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/bin/resol-vbus/src/file-list-reader.js',
    '/bin/resol-vbus/src/index.js',
    '/bin/resol-vbus/examples/resol-vbus.js',
    '/bin/resol-vbus/examples/json-live-data-server/index.js'
  ]
}
```

The installation process is documented here: https://github.com/dm82m/hassio-addons/blob/main/resol-vbus/Dockerfile

**Comment by dm82m** [comment]
node version: v12.22.12

**Comment by ChR-iSz** [comment]
`npm install fs.promises`

**Comment by dm82m** [comment]
fixed it by manually installing the current nodejs version instead of sticking with the default one provided by package sources
