### ISSUE TITLE
Support for Vitosolic 200

### ISSUE THREAD

**Issue by epenet** [danielwippermann/resol-vbus#98]
Hi,

I have a Vitosolic 200, and I would like to be able to change the settings dynamically on my controller.
In particular, I would like to be able to be able to:
- change the priority between two tanks (switch between "1" and "2" on `0x1000` and on `0x1001`)
- force the pump relay at regular interval to avoid (switch between "on", "auto" and "off" on `0x01F1` and on `0x01F4`)

I was able to confirm this works using the RESOL ServiceCenter, but when I tried your `customizer` I got the following error
```
Connecting...
Connection state changed to CONNECTING
Connection state changed to CONNECTED
Waiting for free bus...
Found master with address 0x7321
WARNING: Unable to create optimizer for master with address 0x7321
[1] Optimizing set of values for round 1
Disconnecting...
Connection state changed to DISCONNECTING
TypeError: Cannot read properties of null (reading 'optimizeLoadConfiguration')
    at ConnectionCustomizer._optimizeLoadConfiguration (_\resol-vbus\src\customizer.js:146:31)
    at callback (_\resol-vbus\src\connection-customizer.js:89:29)
    at ConnectionCustomizer.transceiveConfiguration (_\resol-vbus\src\connection-customizer.js:210:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runSingleShot (_\resol-vbus\examples\customizer\index.js:152:28)
    at async main (_\resol-vbus\examples\customizer\index.js:222:16)
Connection state changed to DISCONNECTED
```

and with `customizer2` I got the following errors
```
Waiting for free bus...
Got bus offer from 0x7321, getting changeset...
Unable to get changeset, using 0 as default
Loading value info cache from C:\dev\github\resol-vbus\examples\customizer2\cache\7321_00000000.json...
Cache loaded! Cached entry count: 0
Known values: 0, unknown values: 0
Valid values: 0, invalid values: 0, unknown values: 0!
Releasing bus...
Bus released!
```

I assume that I have to create some files in `src/configuration-optimizers` but I'm not sure how!

**Comment by epenet** [comment]
I managed to get the parametrization sample working with the changes in #99

Now I would still love to get it working via the` customizer2`...

**Comment by danielwippermann** [comment]
Hi @epenet !

Glad you worked out a interim solution!

Since all the controllers I can access for testing purposes support the more moderen parameterization features like changeset detection etc. I cannot really test the Vitosolic's behaviour myself. But I have made a couple of changes to the "customizer2" example in commit 2551359e886b6ac3843e84f74ef6be62873d84b6 that should improve support for older controllers. In addition to that I added a new example `load-job3.json` for such a case where the "valueIndex" has been specified manually:

https://github.com/danielwippermann/resol-vbus/blob/2551359e886b6ac3843e84f74ef6be62873d84b6/examples/customizer2/test/fixtures/load-job3.json

I'd really appreciate if you could test those changes against your Vitosolic controller.

Best regards, Daniel

**Comment by epenet** [comment]
Excellent, it is working. as expected.
Below a couple of corresponding logs.

[load.log](https://github.com/danielwippermann/resol-vbus/files/14125266/load.log)
[save.log](https://github.com/danielwippermann/resol-vbus/files/14125267/save.log)

One more question based on the logs... it seems that we are receiving an "ack" from the vitosolic after every Tx.
I can't seem to find this structure (`0xAA + four bytes`) in the documentation.

```
Tx `0xAA 0x21 0x73 0x20 0x00 0x20 0x00 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x28`
Rx `0xAA 0x21 0x00 0x00 0x28`

Tx `0xAA 0x21 0x73 0x20 0x00 0x20 0x00 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x28`
Rx `0xAA 0x21 0x00 0x00 0x28`

Tx `0xAA 0x21 0x73 0x20 0x00 0x20 0x00 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x28`
Rx `0xAA 0x21 0x00 0x00 0x28`

Tx `0xAA 0x21 0x73 0x20 0x00 0x20 0x00 0x02 0x00 0x10 0x01 0x00 0x00 0x00 0x00 0x18`
Rx `0xAA 0x21 0x00 0x00 0x18 `
Rx `0xAA 0x20 0x00 0x21 0x73 0x20 0x00 0x01 0x00 0x10 0x01 0x00 0x00 0x00 0x00 0x19`
```

**Comment by danielwippermann** [comment]
Hmmm, that seems to be junk. All VBus primitives need at least five bytes after the 0xAA to determine the version to use. And hence the 0xAA + four bytes do not form valid VBus data. But there is a pattern in your dump:

```
Tx `0xAA 0x21 0x73 0x20 0x00 0x20 0x00 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x28`
Rx `0xAA 0x21 .... .... .... .... .... .... .... .... .... .... .... 0x00 0x00 0x28`

Tx `0xAA 0x21 0x73 0x20 0x00 0x20 0x00 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x28`
Rx `0xAA 0x21 .... .... .... .... .... .... .... .... .... .... .... 0x00 0x00 0x28`

Tx `0xAA 0x21 0x73 0x20 0x00 0x20 0x00 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x28`
Rx `0xAA 0x21 .... .... .... .... .... .... .... .... .... .... .... 0x00 0x00 0x28`

Tx `0xAA 0x21 0x73 0x20 0x00 0x20 0x00 0x02 0x00 0x10 0x01 0x00 0x00 0x00 0x00 0x18`
Rx `0xAA 0x21 .... .... .... .... .... .... .... .... .... .... .... 0x00 0x00 0x18`
Rx `0xAA 0x20 0x00 0x21 0x73 0x20 0x00 0x01 0x00 0x10 0x01 0x00 0x00 0x00 0x00 0x19`
```

It is quiet normal that you receive an echo of all the data you send through the VBus adapter. That is a side effect of the VBus hardware.

So I assume that the dotted bytes in the sequences above are dropped bytes from the echo. Perhaps your VBus adapter has some sort of echo squelch.

Nevertheless: the short "responses" you see start with the same `0xAA 0x21` as your TX. And the `0x21` is the lower byte of the destination address, which most likely is directed to your Vitosolic.

Best regards,
Daniel
